version: '3.2'
services:
  plugin:
    image: quay.io/arcalot/arcaflow-plugin-horreum-client
    build: .
    volumes:
      - source: ./example.yaml
        target: /config/example.yaml
        type: bind
